apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: iterate-sample
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
  labels:
    app.kubernetes.io/part-of: iterate-sample
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: iterate-sample
    app.kubernetes.io/component: run
    carto.run/workload-name: iterate-sample
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
          appliveview-sample/app-live-view-appflavour-check
          appliveview-sample/app-live-view-connector-steeltoe
          appliveview-sample/app-live-view-appflavours-steeltoe
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: iterate-sample
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: iterate-sample
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.flavours: steeltoe
        tanzu.app.live.view.application.name: iterate-sample
    spec:
      containers:
      - image: 375783000519.dkr.ecr.us-west-2.amazonaws.com/tanzu-application-platform/iterate-sample-mae@sha256:519447caed9101b5a1eb40f5f62aad6aac39e3bd0ac53315af130653684e0d7f
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

